import type { Metadata } from 'next';
import './../styles/globals.css';
import { Lato } from 'next/font/google';
import { Providers } from './providers';

const lato = Lato({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Around the world',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} h-screen w-screen bg-pink`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
